In [6]:
import numpy as np

In [8]:
a=[1,2,3,4,5,7]

In [27]:
b=np.array(a,int)
c=np.array([3,1,4,1,5,9],int)
b,c

(array([1, 2, 3, 4, 5, 7]), array([3, 1, 4, 1, 5, 9]))

In [16]:
e=np.zeros(6)
f=np.ones(5)
g=np.linspace(1,11,6)
e,f,g

(array([0., 0., 0., 0., 0., 0.]),
 array([1., 1., 1., 1., 1.]),
 array([ 1.,  3.,  5.,  7.,  9., 11.]))

In [25]:
b*c

array([ 3,  2, 12,  4, 25, 63])

In [26]:
np.dot(b,c)

109

In [28]:
a=np.array([1,2,3,4])

In [29]:
b=np.array([[5,-2],[-2,5]])
c=np.array([[2,3],[3,5]])
b, c

(array([[ 5, -2],
        [-2,  5]]),
 array([[2, 3],
        [3, 5]]))

In [30]:
np.dot(b,c)

array([[ 4,  5],
       [11, 19]])

In [31]:
np.linalg.eig(b)##linalg에서 b의 eigenvalue를 구하라

(array([7., 3.]),
 array([[ 0.70710678,  0.70710678],
        [-0.70710678,  0.70710678]]))

In [32]:
np.linalg.inv(b)##linalg에서 b의 역행렬을 구하라

array([[0.23809524, 0.0952381 ],
       [0.0952381 , 0.23809524]])

In [33]:
[i*2 for i in [1,2,3]]

[2, 4, 6]

In [34]:
[i for i in range(10)]

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [35]:
a=[1,2,3,4,5]

In [37]:
b=[i*5 for i in a]
b

[5, 10, 15, 20, 25]

In [38]:
c=[]
for i in a:
    c.append(i*5)
c

[5, 10, 15, 20, 25]

In [39]:
##문자열 다루기

In [53]:
'deep learning '

'deep learning '

In [41]:
"shallow learning"

'shallow learning'

In [42]:
'123 4'

'123 4'

In [55]:
a='deep learning '

In [45]:
a[0], a[3], a[4], a[-1]

('d', 'p', ' ', 'g')

In [46]:
a[2:6]

'ep l'

In [52]:
b='3.14'
f=' is good'
a+f

'deep learning is good'

In [57]:
a*3

'deep learning deep learning deep learning '

In [58]:
print("3.14")

3.14


In [59]:
a=2
b=3.14

In [63]:
print(a,b)

2 3.14


In [65]:
f=open("save.txt","w")
f.write("5")
f.close()

In [66]:
##함수(function)

In [67]:
import numpy as np

In [68]:
2**3

8

In [71]:
# 3^5
a, b=3, 5
p=1

for i in range(1,b+1):
    p=p*a
p


243

In [74]:
def power(x,y):
    p=1
    for i in range(1,b+1):
        p=p*a
    return p, a, b

In [75]:
power(3,5)

(243, 3, 5)